<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>b8de8673-7ca3-4ad7-87d7-fdde1d455a36</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.86" />
    <PackageReference Include="dbup" Version="5.0.41" />
    <PackageReference Include="dbup-postgresql" Version="7.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.20" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="..\database\*.sql" />
	</ItemGroup>

</Project>
